package com.myproject.Form;

import com.myproject.DAO.NhanVienDao;
import com.myproject.Model.NhanVien;
import com.myproject.UI.Application;

import com.myproject.swing.ScrollBar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author PC
 */
public class Form_QLYNHANVIEN extends javax.swing.JPanel {

    private NhanVienDao nhanVienDao = new NhanVienDao();
    private DefaultTableModel tableModel;

    public JPanel getPanel() {
        return p_nhanvien;
    }

    public Form_QLYNHANVIEN() {
        initComponents();
        spTable.setVerticalScrollBar(new ScrollBar());
        loadNhanViens();

    }
   @Override
    public void addNotify() {
    super.addNotify();
    adjustPanelSize();
}
  private void adjustPanelSize() {
    // Get the screen dimensions
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int screenHeight = screenSize.height;
    
  int phandauHeight = p_phandau.getHeight();
    
    // Get the height of Header from the Application class
    Application application = (Application) SwingUtilities.getWindowAncestor(this);
    JPanel headerPanel = application.getHeader();
    int headerHeight = headerPanel.getHeight();

    // Calculate the new height for p_sanpham
    int newNhanVienPanelHeight = screenHeight - (450 + headerHeight);
    System.out.println("Độ dài của phandauHeight"+phandauHeight);
    System.out.println("Độ dài của headerPanel"+headerHeight);
    System.out.println("Độ dài của p_sanpham"+newNhanVienPanelHeight);

    // Set the new size for p_sanpham
    setSizeTable(p_nhanvien, p_nhanvien.getWidth(), newNhanVienPanelHeight);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butradio_gioitinh = new javax.swing.ButtonGroup();
        p_phandau = new javax.swing.JPanel();
        p_thongtin = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtSĐT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnAdd = new com.myproject.swing.Button();
        btnEdit = new com.myproject.swing.Button();
        btnDelete = new com.myproject.swing.Button();
        btnLamMoi = new com.myproject.swing.Button();
        btnHienThiTable = new com.myproject.swing.Button();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        btnTimKiem = new com.myproject.swing.Button();
        p_nhanvien = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btn_setsizeTable = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btn_phong = new javax.swing.JPanel();
        btn_setSizeTable = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        spTable = new javax.swing.JScrollPane();
        tbl_NhanVien = new com.myproject.swing.Table();

        setBackground(new java.awt.Color(227, 224, 224));
        setLayout(new java.awt.BorderLayout());

        p_phandau.setBackground(new java.awt.Color(197, 194, 194));
        p_phandau.setPreferredSize(new java.awt.Dimension(1100, 400));
        p_phandau.setRequestFocusEnabled(false);
        p_phandau.setLayout(new java.awt.BorderLayout());

        p_thongtin.setBackground(new java.awt.Color(197, 194, 194));
        p_thongtin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p_thongtin.setFocusCycleRoot(true);
        p_thongtin.setRequestFocusEnabled(false);
        p_thongtin.setLayout(new javax.swing.BoxLayout(p_thongtin, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(227, 224, 224));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setPreferredSize(new java.awt.Dimension(550, 300));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(227, 224, 224));
        jPanel8.setPreferredSize(new java.awt.Dimension(600, 374));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel1.setText("Họ và tên");
        jLabel1.setToolTipText("");

        txtHoVaTen.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtHoVaTen.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtHoVaTen.setMinimumSize(new java.awt.Dimension(64, 33));
        txtHoVaTen.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("Giới tính");
        jLabel2.setToolTipText("");

        rdoNam.setBackground(new java.awt.Color(227, 224, 224));
        butradio_gioitinh.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });

        rdoNu.setBackground(new java.awt.Color(227, 224, 224));
        butradio_gioitinh.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        rdoNu.setText("Nữ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("Số điện thoại");

        txtSĐT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtSĐT.setMinimumSize(new java.awt.Dimension(64, 33));
        txtSĐT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSĐTActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtEmail.setMinimumSize(new java.awt.Dimension(64, 33));

        jPanel7.setBackground(new java.awt.Color(227, 224, 224));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 374));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(51, 51, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8-add-24.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel7.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 37));
        btnAdd.getAccessibleContext().setAccessibleDescription("");

        btnEdit.setBackground(new java.awt.Color(51, 51, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8-edit-24.png"))); // NOI18N
        btnEdit.setText("Cập nhật");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel7.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 37));

        btnDelete.setBackground(new java.awt.Color(51, 51, 255));
        btnDelete.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8-delete-24.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel7.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 37));

        btnLamMoi.setBackground(new java.awt.Color(51, 51, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel7.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 37));

        btnHienThiTable.setBackground(new java.awt.Color(51, 51, 255));
        btnHienThiTable.setText("Danh sách");
        btnHienThiTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiTableActionPerformed(evt);
            }
        });
        jPanel7.add(btnHienThiTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 37));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSĐT, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHoVaTen, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel1)
                                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(rdoNam,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 63,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(rdoNu)))
                                                .addGap(0, 630, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel8Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(rdoNam)
                                                        .addComponent(rdoNu))
                                                .addContainerGap(25, Short.MAX_VALUE))
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE))));

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        p_thongtin.add(jPanel5);

        p_phandau.add(p_thongtin, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(197, 194, 194));
        jPanel3.setPreferredSize(new java.awt.Dimension(1060, 60));

        jPanel6.setBackground(new java.awt.Color(197, 194, 194));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel12.setBackground(new java.awt.Color(227, 224, 224));
        jPanel12.setPreferredSize(new java.awt.Dimension(733, 100));

        txtTimKiem.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        txtTimKiem.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtTimKiem.setPreferredSize(new java.awt.Dimension(64, 33));
        txtTimKiem.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addContainerGap(151, Short.MAX_VALUE)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 639,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE)));

        jPanel6.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(227, 224, 224));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 72));

        btnTimKiem.setBackground(new java.awt.Color(0, 0, 0));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/search_26px.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(159, Short.MAX_VALUE)));
        jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)));

        jPanel6.add(jPanel13);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE));

        p_phandau.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        add(p_phandau, java.awt.BorderLayout.PAGE_START);

        p_nhanvien.setBackground(new java.awt.Color(197, 194, 194));
        p_nhanvien.setPreferredSize(new java.awt.Dimension(1266, 330));
        p_nhanvien.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(227, 224, 224));
        jPanel9.setPreferredSize(new java.awt.Dimension(1110, 40));
        jPanel9.setLayout(new java.awt.BorderLayout());

        btn_setsizeTable.setBackground(new java.awt.Color(227, 224, 224));
        btn_setsizeTable.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(227, 224, 224));

        btn_phong.setBackground(new java.awt.Color(227, 224, 224));
        btn_phong.setLayout(new java.awt.BorderLayout());

        btn_setSizeTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_setSizeTable
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/maximize.png"))); // NOI18N
        btn_setSizeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_setSizeTableMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_setSizeTableMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_setSizeTableMouseExited(evt);
            }
        });
        btn_phong.add(btn_setSizeTable, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addContainerGap(36, Short.MAX_VALUE)
                                .addComponent(btn_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_phong, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        btn_setsizeTable.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel14.setBackground(new java.awt.Color(227, 224, 224));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel6.setText("BẢNG NHÂN VIÊN");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addContainerGap(770, Short.MAX_VALUE)));
        jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addContainerGap()));

        btn_setsizeTable.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel9.add(btn_setsizeTable, java.awt.BorderLayout.CENTER);

        p_nhanvien.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBackground(new java.awt.Color(227, 224, 224));

        spTable.setBorder(null);

        tbl_NhanVien.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbl_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã NV", "Họ và tên", "Giới tính", "Số điện thoại", "Email"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tbl_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhanVienMouseClicked(evt);
            }
        });
        spTable.setViewportView(tbl_NhanVien);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                .addContainerGap()));

        p_nhanvien.add(jPanel11, java.awt.BorderLayout.CENTER);

        add(p_nhanvien, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimKiemActionPerformed
        String searchText = txtTimKiem.getText().trim();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin cần tìm kiếm", "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<NhanVien> nhanViens = nhanVienDao.searchNhanViens(searchText);
        updateTable(nhanViens);
    }// GEN-LAST:event_btnTimKiemActionPerformed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rdoNamActionPerformed

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rdoNuActionPerformed

    private void txtSĐTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSĐTActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtSĐTActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!validateForm()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập họ và tên nhân viên", "Thông báo",
                    JOptionPane.ERROR_MESSAGE);
            return; // Nếu validate không thành công, dừng lại
        }
        String hoVaTen = txtHoVaTen.getText().trim();
        NhanVien nv = nhanVienDao.getNhanVienTonTai(hoVaTen);
        if (nv != null) {
            JOptionPane.showMessageDialog(this, "Nhân viên đã tồn tại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int gioiTinh = rdoNam.isSelected() ? 1 : 0;

        String email = txtEmail.getText().trim();
        String soDienThoai = txtSĐT.getText().trim();

        // Tạo đối tượng NhanVien
        NhanVien nhanVien = new NhanVien();
        nhanVien.setHoVaTen(hoVaTen);
        nhanVien.setGioiTinh(gioiTinh);
        nhanVien.setEmail(email);
        nhanVien.setSoDienThoai(soDienThoai);

        // Gọi đến DAO để thêm mới
        boolean added = nhanVienDao.addNhanVien(nhanVien);

        if (added) {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            // Cập nhật lại bảng
            loadNhanViens();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (!validateForm()) {
            return; // Nếu validate không thành công, dừng lại
        }

        int rowIndex = tbl_NhanVien.getSelectedRow();
        if (rowIndex == -1) {
            // Xử lý khi không có dòng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần cập nhật", "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int maNhanVien = (int) tbl_NhanVien.getValueAt(rowIndex, 0);
        String hoVaTen = txtHoVaTen.getText().trim();
        int gioiTinh = rdoNam.isSelected() ? 1 : 0;
        String email = txtEmail.getText().trim();
        String soDienThoai = txtSĐT.getText().trim();

        // Tạo đối tượng NhanVien
        NhanVien nhanVien = new NhanVien();
        nhanVien.setMaNhanVien(maNhanVien);
        nhanVien.setHoVaTen(hoVaTen);
        nhanVien.setGioiTinh(gioiTinh);
        nhanVien.setEmail(email);
        nhanVien.setSoDienThoai(soDienThoai);

        // Gọi đến DAO để cập nhật
        boolean updated = nhanVienDao.updateNhanVien(nhanVien);

        if (updated) {
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            // Cập nhật lại bảng
            loadNhanViens();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int rowIndex = tbl_NhanVien.getSelectedRow();
        if (rowIndex == -1) {
            // Xử lý khi không có dòng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Lấy thông tin từ bảng
        int maNhanVien = (int) tbl_NhanVien.getValueAt(rowIndex, 0);

        // Hỏi xác nhận xóa
        int option = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa nhân viên này.\nToàn bộ thông tin về nhân viên này sẽ bị xóa?",
                "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Gọi đến DAO để xóa
            boolean del = nhanVienDao.deleteAllNhanVienData(maNhanVien);

            if (del) {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công", "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE);
                // Cập nhật lại bảng
                loadNhanViens();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên không thành công", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_btnDeleteActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtHoVaTen.setText("");
        txtEmail.setText("");
        rdoNam.setSelected(true);
        rdoNu.setSelected(true);
        txtSĐT.setText("");
    }// GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHienThiTableActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHienThiTableActionPerformed
        // TODO add your handling code here:
        loadNhanViens();
    }// GEN-LAST:event_btnHienThiTableActionPerformed

    private void btn_setSizeTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_setSizeTableMouseClicked

        int newHeight;

        if (p_phandau.isVisible()) {
            p_phandau.setVisible(false);
            newHeight = 720;
        } else {
            p_phandau.setVisible(true);
            newHeight = 330;

        }

        setSizeTable(p_nhanvien, getWidth(), newHeight);

    }// GEN-LAST:event_btn_setSizeTableMouseClicked

    private void btn_setSizeTableMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_setSizeTableMouseEntered
        changecolor(btn_phong, new Color(204, 204, 204));
    }// GEN-LAST:event_btn_setSizeTableMouseEntered

    private void btn_setSizeTableMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_setSizeTableMouseExited
        changecolor(btn_phong, new Color(227, 224, 224));
    }// GEN-LAST:event_btn_setSizeTableMouseExited

    private void tbl_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbl_NhanVienMouseClicked
        int selectedRow = tbl_NhanVien.getSelectedRow();
        if (selectedRow != -1) {
            try {
                // Lấy mã nhân viên từ dòng được chọn
                int maNhanVien = (int) tableModel.getValueAt(selectedRow, 0); // Giả sử maNhanVien ở cột đầu tiên
                NhanVien selectedNhanVien = nhanVienDao.getNhanVienById(maNhanVien);

                if (selectedNhanVien != null) {
                    // Đổ dữ liệu của selectedNhanVien vào các trường trên form
                    txtHoVaTen.setText(selectedNhanVien.getHoVaTen());
                    txtSĐT.setText(selectedNhanVien.getSoDienThoai());
                    txtEmail.setText(selectedNhanVien.getEmail());

                    // Hiển thị giới tính
                    if (selectedNhanVien.getGioiTinh() == 1) {
                        rdoNam.setSelected(true);
                    } else {
                        rdoNu.setSelected(true);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi lấy thông tin nhân viên: " + e.getMessage(), "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }// GEN-LAST:event_tbl_NhanVienMouseClicked

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTimKiemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.myproject.swing.Button btnAdd;
    private com.myproject.swing.Button btnDelete;
    private com.myproject.swing.Button btnEdit;
    private com.myproject.swing.Button btnHienThiTable;
    private com.myproject.swing.Button btnLamMoi;
    private com.myproject.swing.Button btnTimKiem;
    private javax.swing.JPanel btn_phong;
    private javax.swing.JLabel btn_setSizeTable;
    private javax.swing.JPanel btn_setsizeTable;
    private javax.swing.ButtonGroup butradio_gioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel p_nhanvien;
    private javax.swing.JPanel p_phandau;
    private javax.swing.JPanel p_thongtin;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JScrollPane spTable;
    private com.myproject.swing.Table tbl_NhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtSĐT;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    public void setSizeTable(JPanel panel, int width, int height) {
        panel.setPreferredSize(new Dimension(width, height));
        panel.revalidate();
        panel.repaint();
    }

    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    private void loadNhanViens() {
        List<NhanVien> nhanViens = nhanVienDao.getAllNhanViens();
        tableModel = (DefaultTableModel) tbl_NhanVien.getModel();
        tableModel.setRowCount(0);

        for (NhanVien nv : nhanViens) {
            tableModel.addRow(new Object[] {
                    nv.getMaNhanVien(),
                    nv.getHoVaTen(),
                    (nv.getGioiTinh() == 1 ? "Nam" : "Nữ"),
                    nv.getSoDienThoai(),
                    nv.getEmail()

            });
        }
    }

    private void updateTable(List<NhanVien> nhanViens) {
        DefaultTableModel model = (DefaultTableModel) tbl_NhanVien.getModel();
        model.setRowCount(0);

        for (NhanVien nv : nhanViens) {
            Object[] rowData = new Object[] {
                    nv.getMaNhanVien(),
                    nv.getHoVaTen(),
                    nv.getGioiTinh() == 1 ? "Nam" : "Nữ",
                    nv.getSoDienThoai(),
                    nv.getEmail()
            };
            model.addRow(rowData);
        }
    }

    // validate form
    private boolean isValidHoTen(String hoTen) {
        return !hoTen.trim().isEmpty();
    }

    private boolean isValidSoDienThoai(String soDienThoai) {
        return soDienThoai.matches("\\d{9,12}");
    }

    private boolean isValidEmail(String email) {
        return email.matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}");
    }

    private boolean isValidGioiTinh() {
        return rdoNam.isSelected() || rdoNu.isSelected(); // Phải chọn ít nhất một trong hai giới tính
    }

    private boolean validateForm() {
        String hoTen = txtHoVaTen.getText().trim();
        String soDienThoai = txtSĐT.getText().trim();
        String email = txtEmail.getText().trim();

        if (!isValidHoTen(hoTen)) {
            return false;
        }
        // if (!isValidSoDienThoai(soDienThoai)) {
        // return false;
        // }
        // if (!isValidEmail(email)) {
        // return false;
        // }
        if (!isValidGioiTinh()) {
            return false;
        }

        return true;
    }
}
