package com.myproject.UI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.myproject.Form.CHAO;
import com.myproject.Form.Form_QLYNHANVIEN;
import com.myproject.Form.Form_QLYSANPHAM;
import com.myproject.Form.Form_THONGKE;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class Application extends javax.swing.JFrame {

    boolean a = true;
    //private Form_NHIEMVU form_tinhluong;
    private Form_QLYNHANVIEN form_qlynhanvien;
    private Form_QLYSANPHAM form_qlysanpham1;
    private Form_THONGKE form_thongke;

    /**
     * Creates new form MainJFrame
     */
    public Application() {
        initComponents();
        setLocationRelativeTo(null);
        //form_tinhluong = new Form_NHIEMVU();
        form_qlynhanvien = new Form_QLYNHANVIEN();
        form_qlysanpham1 = new Form_QLYSANPHAM();
        form_thongke = new Form_THONGKE();
        // test = new testForm();
        setButtonColor(btn_Thongke, lbl_Thongke, form_thongke);
        // Lấy kích thước màn hình
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Insets screenInsets = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());

        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        // Trừ đi chiều cao của taskbar (phía dưới)
        int taskbarHeight = screenInsets.bottom;

        // Thiết lập kích thước cho JFrame
        setBounds(0, 0, screenWidth, screenHeight - taskbarHeight);

    }
    public JPanel getHeader(){
        return Header;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        icon = new javax.swing.JPanel();
        btn_close = new javax.swing.JPanel();
        closeDB = new javax.swing.JLabel();
        btn_maxsize = new javax.swing.JPanel();
        fullscreen = new javax.swing.JLabel();
        btn_minisize = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        menushow = new javax.swing.JPanel();
        btn_showmenu = new javax.swing.JLabel();
        MenuHide = new javax.swing.JPanel();
        btn_Thongke = new javax.swing.JPanel();
        lbl_Thongke = new javax.swing.JLabel();
        btn_qlysanpham = new javax.swing.JPanel();
        lbl_qlysanpham = new javax.swing.JLabel();
        btn_qlynhanvien = new javax.swing.JPanel();
        lbl_qlynhanvien = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(234, 19, 19));
        Header.setFocusCycleRoot(true);
        Header.setPreferredSize(new java.awt.Dimension(1930, 80));
        Header.setLayout(new java.awt.BorderLayout());

        icon.setBackground(new java.awt.Color(234, 19, 19));
        icon.setPreferredSize(new java.awt.Dimension(150, 80));
        icon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_close.setBackground(new java.awt.Color(234, 19, 19));
        btn_close.setLayout(new java.awt.BorderLayout());

        closeDB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/close.png"))); // NOI18N
        closeDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeDBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeDBMouseExited(evt);
            }
        });
        btn_close.add(closeDB, java.awt.BorderLayout.CENTER);

        icon.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        btn_maxsize.setBackground(new java.awt.Color(234, 19, 19));
        btn_maxsize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maxsizeMouseClicked(evt);
            }
        });
        btn_maxsize.setLayout(new java.awt.BorderLayout());

        fullscreen.setBackground(new java.awt.Color(186, 187, 225));
        fullscreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullscreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/minus-grosses-symbol.png"))); // NOI18N
        fullscreen.setToolTipText("");
        fullscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullscreenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullscreenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullscreenMouseExited(evt);
            }
        });
        btn_maxsize.add(fullscreen, java.awt.BorderLayout.CENTER);

        icon.add(btn_maxsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        btn_minisize.setBackground(new java.awt.Color(234, 19, 19));
        btn_minisize.setLayout(new java.awt.BorderLayout());
        icon.add(btn_minisize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Header.add(icon, java.awt.BorderLayout.LINE_END);

        Logo.setBackground(new java.awt.Color(234, 19, 19));
        Logo.setPreferredSize(new java.awt.Dimension(400, 80));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HELIUM MEDIA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel2.setText("l");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8_menu_48px_1.png"))); // NOI18N
        jLabel8.setText("jLabel1");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Header.add(Logo, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(102, 102, 102));
        Menu.setPreferredSize(new java.awt.Dimension(310, 469));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(102, 102, 102));
        MenuIcon.setMinimumSize(new java.awt.Dimension(50, 100));
        MenuIcon.setPreferredSize(new java.awt.Dimension(60, 790));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menushow.setBackground(new java.awt.Color(89, 86, 86));
        menushow.setPreferredSize(new java.awt.Dimension(50, 50));
        menushow.setLayout(new java.awt.BorderLayout());

        btn_showmenu.setBackground(new java.awt.Color(89, 86, 86));
        btn_showmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_showmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/back.png"))); // NOI18N
        btn_showmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_showmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_showmenuMouseExited(evt);
            }
        });
        menushow.add(btn_showmenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(menushow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 70));

        Menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        MenuHide.setBackground(new java.awt.Color(89, 86, 86));
        MenuHide.setMinimumSize(new java.awt.Dimension(290, 420));
        MenuHide.setPreferredSize(new java.awt.Dimension(350, 790));
        MenuHide.setVerifyInputWhenFocusTarget(false);
        MenuHide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Thongke.setBackground(new java.awt.Color(89, 86, 86));
        btn_Thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongkeMouseClicked(evt);
            }
        });

        lbl_Thongke.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_Thongke.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/google_forms_24px.png"))); // NOI18N
        lbl_Thongke.setText("Thống kê");

        javax.swing.GroupLayout btn_ThongkeLayout = new javax.swing.GroupLayout(btn_Thongke);
        btn_Thongke.setLayout(btn_ThongkeLayout);
        btn_ThongkeLayout.setHorizontalGroup(
            btn_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Thongke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        btn_ThongkeLayout.setVerticalGroup(
            btn_ThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ThongkeLayout.createSequentialGroup()
                .addComponent(lbl_Thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuHide.add(btn_Thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        btn_qlysanpham.setBackground(new java.awt.Color(89, 86, 86));
        btn_qlysanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qlysanphamMouseClicked(evt);
            }
        });

        lbl_qlysanpham.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_qlysanpham.setForeground(new java.awt.Color(153, 153, 153));
        lbl_qlysanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/categorize_24px.png"))); // NOI18N
        lbl_qlysanpham.setText("Quản lý sản phẩm");

        javax.swing.GroupLayout btn_qlysanphamLayout = new javax.swing.GroupLayout(btn_qlysanpham);
        btn_qlysanpham.setLayout(btn_qlysanphamLayout);
        btn_qlysanphamLayout.setHorizontalGroup(
            btn_qlysanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_qlysanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        btn_qlysanphamLayout.setVerticalGroup(
            btn_qlysanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlysanphamLayout.createSequentialGroup()
                .addComponent(lbl_qlysanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuHide.add(btn_qlysanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 70));

        btn_qlynhanvien.setBackground(new java.awt.Color(89, 86, 86));

        lbl_qlynhanvien.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_qlynhanvien.setForeground(new java.awt.Color(153, 153, 153));
        lbl_qlynhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/add_user_group_woman_man_24px.png"))); // NOI18N
        lbl_qlynhanvien.setText("Quản lý nhân viên");
        lbl_qlynhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_qlynhanvienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_qlynhanvienLayout = new javax.swing.GroupLayout(btn_qlynhanvien);
        btn_qlynhanvien.setLayout(btn_qlynhanvienLayout);
        btn_qlynhanvienLayout.setHorizontalGroup(
            btn_qlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_qlynhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        btn_qlynhanvienLayout.setVerticalGroup(
            btn_qlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlynhanvienLayout.createSequentialGroup()
                .addComponent(lbl_qlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuHide.add(btn_qlynhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 70));

        Menu.add(MenuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        Dashboard.setBackground(new java.awt.Color(227, 224, 224));
        Dashboard.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Dashboard, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 1370, 750);
    }// </editor-fold>//GEN-END:initComponents

    private void closeDBMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeDBMouseEntered
        changecolor(btn_close, new Color(204, 204, 204));
    }// GEN-LAST:event_closeDBMouseEntered

    private void closeDBMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeDBMouseExited
        changecolor(btn_close, new Color(234, 19, 19));
    }// GEN-LAST:event_closeDBMouseExited

    private void closeDBMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_closeDBMouseClicked
        System.exit(0);
    }// GEN-LAST:event_closeDBMouseClicked

    private void fullscreenMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_fullscreenMouseEntered
        changecolor(btn_maxsize, new Color(204, 204, 204));
    }// GEN-LAST:event_fullscreenMouseEntered

    private void fullscreenMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_fullscreenMouseExited
        changecolor(btn_maxsize, new Color(234, 19, 19));
    }// GEN-LAST:event_fullscreenMouseExited

    private void fullscreenMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_fullscreenMouseClicked
        this.setState(Application.ICONIFIED);
    }// GEN-LAST:event_fullscreenMouseClicked

    private void btn_showmenuMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_showmenuMouseEntered

    }// GEN-LAST:event_btn_showmenuMouseEntered

    private void btn_showmenuMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_showmenuMouseExited

    }// GEN-LAST:event_btn_showmenuMouseExited

    private void btn_showmenuMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_showmenuMouseClicked
        // TODO add your handling code here:
        clickmenu(menushow, 1);
        if (a == true) {
            hideshow(Menu, a);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;
        } else {
            hideshow(Menu, a);
            SwingUtilities.updateComponentTreeUI(this);
            a = true;
        }
    }// GEN-LAST:event_btn_showmenuMouseClicked

    private void btn_maxsizeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_maxsizeMouseClicked

    }// GEN-LAST:event_btn_maxsizeMouseClicked

    private void lbl_qlynhanvienMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbl_qlynhanvienMouseClicked
        setButtonColor(btn_qlynhanvien, lbl_qlynhanvien, form_qlynhanvien);
    }// GEN-LAST:event_lbl_qlynhanvienMouseClicked

    private void btn_qlysanphamMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_qlysanphamMouseClicked
        setButtonColor(btn_qlysanpham, lbl_qlysanpham, form_qlysanpham1);
    }// GEN-LAST:event_btn_qlysanphamMouseClicked

    private void btn_ThongkeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_ThongkeMouseClicked
        setButtonColor(btn_Thongke, lbl_Thongke, form_thongke);
    }// GEN-LAST:event_btn_ThongkeMouseClicked

    private void btn_TinhluongMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_TinhluongMouseClicked
        setButtonColor(btn_Thongke, lbl_Thongke, form_thongke);
    }// GEN-LAST:event_btn_TinhluongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                showSplashScreen(new Application());
                ImageIcon iconlogo = new ImageIcon(getClass().getResource("/com/myproject/Image/icon-logo.png"));
                Application mainJFrame = new Application();
                mainJFrame.setIconImage(iconlogo.getImage());
                mainJFrame.setVisible(true);
            }
        });
    }

    private static void showSplashScreen(JFrame jFrame) {
        CHAO splash = new CHAO(null, true);
        splash.setVisible(true);
        try {

            splash.dispose();
            Thread.sleep(250);

        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuHide;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel btn_Thongke;
    private javax.swing.JPanel btn_close;
    private javax.swing.JPanel btn_maxsize;
    private javax.swing.JPanel btn_minisize;
    private javax.swing.JPanel btn_qlynhanvien;
    private javax.swing.JPanel btn_qlysanpham;
    private javax.swing.JLabel btn_showmenu;
    private javax.swing.JLabel closeDB;
    private javax.swing.JLabel fullscreen;
    private javax.swing.JPanel icon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_Thongke;
    private javax.swing.JLabel lbl_qlynhanvien;
    private javax.swing.JLabel lbl_qlysanpham;
    private javax.swing.JPanel menushow;
    // End of variables declaration//GEN-END:variables

    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    public void hideshow(JPanel menushow, boolean dashboard) {
        if (dashboard == true) {
            menushow.setPreferredSize(new Dimension(60, menushow.getHeight()));
        } else {
            menushow.setPreferredSize(new Dimension(310, menushow.getHeight()));
        }
    }

    public void clickmenu(JPanel h1, int num) {
        if (num == 1) {
            h1.setBackground(new Color(89, 86, 86));
        } else {
            h1.setBackground(new Color(243, 237, 237));
        }
    }

    private void resetForm() {
        form_qlynhanvien = new Form_QLYNHANVIEN();
        form_qlysanpham1 = new Form_QLYSANPHAM();
        form_thongke = new Form_THONGKE();
    //    form_tinhluong = new Form_NHIEMVU();
    }

    public void setButtonColor(javax.swing.JPanel selectedButton, JLabel label, JPanel panelShow) {

        // reset form
        resetForm();

        Color selectColor = new Color(227, 224, 224);
        Color defaultColor = new Color(89, 86, 86);
        Color lblColor = new Color(153, 153, 153);

        //lbl_TinhLuong.setForeground(lblColor);
        lbl_qlynhanvien.setForeground(lblColor);
        lbl_qlysanpham.setForeground(lblColor);
        lbl_Thongke.setForeground(lblColor);
        //
        btn_Thongke.setBackground(defaultColor);
       // btn_Tinhluong.setBackground(defaultColor);
        btn_qlysanpham.setBackground(defaultColor);
        btn_qlynhanvien.setBackground(defaultColor);
        //
        label.setForeground(new Color(0, 0, 0));

        selectedButton.setBackground(selectColor);

        Dashboard.removeAll();
        Dashboard.setLayout(new BorderLayout());
        Dashboard.add(panelShow, BorderLayout.CENTER);
        Dashboard.revalidate();
        Dashboard.repaint();
    }

//    public void setSizeForForm(JPanel panel1) {
//        JPanel p_table = form_tinhluong.getJPanel();
//
//        int footerwidth = 1266;
//        int footerheight = 774;
//        int fw = 1060;
//        int fh = 620;
//        p_table.setPreferredSize(new Dimension(fw, fh));
//        panel1.setPreferredSize(new Dimension(footerwidth, footerheight));
//
//    }

    private void resizePTable(JPanel panel) {
        int currentHeight = panel.getPreferredSize().height;
        int newHeight;
        if (currentHeight == 650) {
            newHeight = 750;
        } else if (currentHeight == 750) {
            newHeight = 650;
        } else if (currentHeight == 200) {
            newHeight = 300;
        } else if (currentHeight == 300) {
            newHeight = 200;
        } else {
            newHeight = 200;
        }

        setSizeTable(panel, panel.getWidth(), newHeight);
    }

    public void setSizeTable(JPanel panel, int width, int height) {
        panel.setPreferredSize(new Dimension(width, height));
        panel.revalidate();
        panel.repaint();
    }
}
